@baseUrl = http://localhost:3000
@authToken = {{authenticate.response.body.accessToken}}
@refreshToken = {{authenticate.response.body.refreshToken}}

# MESSAGES
### Show all messages
GET {{baseUrl}}/messages/
?limit=10
&offset=0
### Show only one message
GET {{baseUrl}}/messages/24/
### Create a message
POST {{baseUrl}}/messages/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "text": "From Eduardo to Kate",
    "toId": 11
}
### Update a message
PATCH {{baseUrl}}/messages/31/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "text": "From Eduardo to Kate Update... ",
    "read": true
}
### Delete a message
DELETE {{baseUrl}}/messages/31/
Authorization: Bearer {{authToken}}



#


# PERSONS
### Show all persons
GET {{baseUrl}}/persons/
?limit=100
&offset=100
Authorization: Bearer {{authToken}}
### Show only one person
GET {{baseUrl}}/persons/12/
Authorization: Bearer {{authToken}}
### Create a person
POST {{baseUrl}}/persons/
Content-Type: application/json

{
   "email": "thiago3@email.com",
   "password": "123456",
   "name": "Thiago",
   "routePolicies": ["createMessage", "findOneMessage"]
}
### Update a person
PATCH {{baseUrl}}/persons/19/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "name": "LUCAS!!"
}
### Delete a person
DELETE {{baseUrl}}/persons/22/
Authorization: Bearer {{authToken}}



#


# AUTH
### Authentication
# @name authenticate
POST {{baseUrl}}/auth/
Content-Type: application/json

{
    "email": "thiago3@email.com",
    "password": "123456"
}

### Re-Authentication
# @name reAuthenticate
POST {{baseUrl}}/auth/refresh/
Content-Type: application/json

{
    "refreshToken": "{{refreshToken}}"
}
