@baseUrl = http://localhost:3000

# Messages
###
GET {{baseUrl}}/messages/
###
GET {{baseUrl}}/messages/1/
###
POST {{baseUrl}}/messages/
Content-Type: application/json

{
    "message": "This is the message im sending.",
    "new-key": "other value"
}

### AppControllerGetHello

# @name AppControllerGetHello
GET {{baseUrl}}/home/second/

### ExampleRoute

# @name ExampleRoute
GET {{baseUrl}}/home/example/

