@baseUrl = http://localhost:3000

# Messages
### Show all messages
GET {{baseUrl}}/messages/?limit=100&offset=100
### Show only one message
GET {{baseUrl}}/messages/5/
### Create a message
POST {{baseUrl}}/messages/
Content-Type: application/json

{
    "text": "New Message",
    "from": "Jennifer",
    "to": "Roma"
}
### Update a message
PATCH {{baseUrl}}/messages/5/
Content-Type: application/json

{
    "text": "Updated Message 5",
    "read": false
}
### Delete a message
DELETE {{baseUrl}}/messages/4/

### AppControllerGetHello

# @name AppControllerGetHello
GET {{baseUrl}}/home/second/

### ExampleRoute

# @name ExampleRoute
GET {{baseUrl}}/home/example/
